name: Deploy (Production)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.details_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Lint (optionnel)
        run: npm run lint --if-present || echo "Lint ignoré"

      - name: Tests (headless)
        run: npm run test -- --watch=false --browsers=ChromeHeadless || echo "Tests ignorés"

      - name: Build (prod)
        run: npm run build

      - name: Deploy to Firebase Hosting (live)
        id: deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: '<TON_ID_FIREBASE>'
          channelId: live
