name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

# Toutes les commandes `run:` s'exécuteront dans le dossier `cv`
defaults:
  run:
    working-directory: cv

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3. Mettre en cache le registre npm
      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('cv/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 4. Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 5. Compiler l’application Angular
      - name: Build Angular app
        run: npm run build -- --configuration production

      # 6. Déployer sur Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: live
          projectId: ton-project-id
